### ISSUE TITLE
使用启动命令时部分服务端无法获取人数信息导致强制重启

### ISSUE THREAD

**Issue by skyfsj** [limbang/mirai-console-mcsm-plugin#3]
服务端：forge1.12.2
![image](https://user-images.githubusercontent.com/47785500/189848334-bc17b333-0f4b-4e08-aa94-a0e69b45d9ae.png)
![image](https://user-images.githubusercontent.com/47785500/189848399-647eaf7a-3e52-43f5-b74c-65b398211ffc.png)

**Comment by skyfsj** [comment]
获取上图中的“模组服1-RLCraft”时不会发生该问题，服务端为Sponge forge

**Comment by limbang** [comment]
试试在服务器发送 list 是否有返回。如果没返回它的逻辑就是靠返回判断服务器是否假死。要不给这个功能加个开关？

**Comment by limbang** [comment]
这个功能主要是假死的时候。群员可以自己启动。 如果其他如人乱发  可以加黑名单。他发的指令就没用了

**Comment by skyfsj** [comment]
![image](https://user-images.githubusercontent.com/47785500/189890608-70e5b459-1bb4-456f-b9b9-a5bd817a7d7c.png)
是有的，我觉得开关可以有

**Comment by skyfsj** [comment]
或者给检测返回加个等待时间，检测等待时间段内的

**Comment by limbang** [comment]
有等待时间的。默认是1秒 你先用这个改成3秒的试试有没有用吧
[mirai-console-mcsm-plugin-1.0.10.mirai2.jar.zip](https://github.com/limbang/mirai-console-mcsm-plugin/files/9556729/mirai-console-mcsm-plugin-1.0.10.mirai2.jar.zip)

**Comment by skyfsj** [comment]
不行，应该是关键字没抓到？

**Comment by skyfsj** [comment]
我看后台是正确输出了人数信息

**Comment by limbang** [comment]
配置文件发我邮箱  495071565@qq.com   我有空的时候调试看看哪的问题  之后你在改下 key

**Comment by limbang** [comment]
我尝试获取了下 /mcsm cmd mod2 list 命令获取到的日志是这样的，里面缺少了通道 [minecraft/DedicatedServer]

[22:53:19] [Server thread/INFO]: There are 0/50 players online:
[22:53:19] [Server thread/INFO]: 

/mcsm cmd lts list

[23:00:21] [Server thread/INFO] [minecraft/DedicatedServer]: There are 4/50 players online:
[23:00:21] [Server thread/INFO] [minecraft/DedicatedServer]: Hookfang, hengxing, stardie, XUQIZXS

![image](https://user-images.githubusercontent.com/6381512/190192627-a198969e-6294-47ce-95cc-36f4358fb853.png)

看了下 你服务器比我快1秒 导致的判断时间

**Comment by limbang** [comment]
[mirai-console-mcsm-plugin-1.0.10.mirai2.jar.zip](https://github.com/limbang/mirai-console-mcsm-plugin/files/9567620/mirai-console-mcsm-plugin-1.0.10.mirai2.jar.zip)
试试这个版本。我把获取时间改到发送之前了

**Comment by skyfsj** [comment]
判断关键字”There are“ ”players online“会不会更好

我看了下API文档，发送命令是有返回执行时的时间戳的，延迟可能得以那个为依据？

**Comment by limbang** [comment]
mod2 是什么端？  我插件参照   forge 写的  
![image](https://user-images.githubusercontent.com/6381512/190196307-9badb388-df38-47f3-b90a-60e8121d6253.png)
日志 有  时间  级别  通道 消息 

时间戳可以。需要改一些东西。有空优化下 你关掉外网访问把。

**Comment by skyfsj** [comment]
1.10.2的forge

**Comment by limbang** [comment]
判断关键字”There are“ ”players online“会不会更好   这样就没法获取下面的名字了
[mirai-console-mcsm-plugin-1.0.10.mirai2.jar.zip](https://github.com/limbang/mirai-console-mcsm-plugin/files/9568407/mirai-console-mcsm-plugin-1.0.10.mirai2.jar.zip)
这是改过的版本 你试试能不能用吧

**Comment by skyfsj** [comment]
![image](https://user-images.githubusercontent.com/47785500/190231095-4431b714-6095-4cc9-af79-1bd5cf77cba8.png)
![image](https://user-images.githubusercontent.com/47785500/190231139-28d38728-6107-4b49-af07-60202918ae0b.png)
这回直接无响应了

**Comment by limbang** [comment]
看看你守护进程的id对不对。昨天你发我的配置文件。守护进程不对
