### ISSUE TITLE
404 找不到api

### ISSUE THREAD

**Issue by ghost** [limbang/mirai-console-mcsm-plugin#4]
实际上好像最新版本的mcsm把api修改了识别不到了。。。

**Comment by ghost** [comment]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/C:/Users/alglt/Desktop/mcl-2.0.1-A版/plugin-libraries/com/squareup/retrofit2/retrofit/2.9.0/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[404] Not Found

**Comment by limbang** [comment]
具体什么命令。使用的什么版本

**Comment by ghost** [comment]
使用的/mcsm daemonList MCSM是9.6.0 后端2.0.0

**Comment by limbang** [comment]
好像 是没变化的 你是不是所有命令都使用不了啊。看看你 mcsm 接口地址

**Comment by ghost** [comment]
对的 我用的是https://xxx.xxxx.xxx 但就是404

**Comment by ghost** [comment]
# mcsm 接口地址
apiUrl: 'https://**.****.xyz'
# mcsm 接口key
apiKey: 7cf****

**Comment by ghost** [comment]
要加/api傻逼了抱歉

**Comment by hewei2723** [comment]
是在接口地址后面添加/api吗，我这里显示404，在http://www.xxxx.xxx后加上/api报错
